# Usa uma imagem oficial do Ruby
FROM ruby:3.3

# Instala dependências do sistema
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos da aplicação
COPY . /app

# Instala as gems
RUN bundle install

# Expõe a porta padrão do Rails
EXPOSE 3000

# Comando padrão para rodar o servidor
CMD ["bin/rails", "server", "-b", "0.0.0.0"]